19 alerting concept
ADORSYS-GIS/webank pull request #29
Opened 2024-09-18 09:44 UTC by Elwizzy12

The pupose of this ticket creating an  alerting concept for the mobile banking application. 
The alerting system is to enhance user engagement, provide timely notifications about important transactions, and ensure the security of user accounts.

2024-09-18 10:10 UTC, Koufan-De-King requested changes

2024-09-18 10:10 UTC, Koufan-De-King commented on docs/concepts/alerting.md
> +By integrating Prometheus for monitoring and Grafana for visualization, the alerting system will be robust and provide valuable insights into application performance and user activity.
I don't believe a conclusion is necessary @Elwizzy12

2024-09-18 11:12 UTC, Blindspot22 requested changes

2024-09-18 11:12 UTC, Blindspot22 commented on docs/concepts/alerting.md
> +### 3.3 Security Alerts
I think you should also include `Alert` for maybe more than 5 or 10 failed login attempts?
What do you think @Elwizzy12  or is that what `unauthorized login attempts` in your description mean?

2024-09-18 21:41 UTC, francis-pouatcha requested changes

2024-09-18 21:41 UTC, francis-pouatcha commented on docs/concepts/alerting.md
I believe there's a misunderstanding between technical alerts and business notifications.

- Initially, we were referring to technical alerts related to the application's state.
- However, business notifications are also something we would eventually need to address.

Please explain the concept of technical alerts here, and move the work related to business notifications into a separate file called **"Requirements for User Notifications."**

2024-09-19 12:53 UTC, Koufan-De-King approved these changes

2024-09-23 06:54 UTC, nancymuyeh approved these changes

2024-09-24 10:18 UTC, francis-pouatcha approved these changes

2024-09-24 10:42 UTC, Blindspot22 approved these changes
Looks Good to Me :100:

2024-09-24 13:53 UTC, merged